nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:4200'] # <--- On autorise Angular ici
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': # On applique cela Ã  toutes les routes API
            allow_origin: ['http://localhost:4200']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['content-type', 'authorization']
            max_age: 3600